### ISSUE TITLE
Unable to dump yaml safely

### ISSUE THREAD

**Issue by ajays20078** [ssato/python-anyconfig#40]
Calling anyconfig.dump(obj, filepath, ac_safe=True) , dumps the config with object references.
Is safe dump supported for yaml files? If yes what argument needs to be passed for it?

**Comment by ajays20078** [comment]
Adding more details:

Input yaml:

key1:
 key2: 2

Output even after safe dumping:

!!python/object/apply:collections.OrderedDict
- - - !!python/unicode 'key1'
    - !!python/object/apply:collections.OrderedDict
      - - [!!python/unicode 'key2', 2]

**Comment by ssato** [comment]
Thanks for your bug report!

I guess that I could fix it with the commit 6226ea61ff5b02aea6d88fa7c3c36687ac41c419 .

```python
In [11]: cnf_s = """key1:
   ....: key2: 2
   ....: """

In [12]: cnf = anyconfig.loads(cnf_s, ac_parser="yaml")

In [13]: cnf
Out[13]: {'key1': None, 'key2': 2}

In [14]: type(cnf)
Out[14]: m9dicts.dicts.UpdateWithMergeDict

In [15]: anyconfig.dumps(cnf, ac_parser="yaml")
Out[15]: '!!python/object/apply:collections.OrderedDict\n- - [key2, 2]\n  - [key1, null]\n'

In [16]: anyconfig.dumps(cnf, ac_parser="yaml", ac_safe=True)
Out[16]: '{key1: null, key2: 2}\n'

In [17]:
```
Could you please check the HEAD ?

**Comment by ajays20078** [comment]
Is there a option to pretty print yaml, as the current dump looks more like json than yaml


Something like:
--- 
key1: ~
key2: 2

instead of 
{key1: null, key2: 2}

**Comment by ajays20078** [comment]
It would be great if pretty printing is supported for all config types with the help of a flag.

**Comment by ssato** [comment]
It seems that PyYAML has the option (default_flow_style) to accomplish that:
http://pyyaml.org/wiki/PyYAMLDocumentation#Dictionarieswithoutnestedcollectionsarenotdumpedcorrectly

Unfortunately, current implementation of anyconfig does not allow passing that option to yaml.dump.
So I fixed it in the commit 9b7a95914f68d5aaba7ee7b3ed36a9603cc8fad2

Could you please try that version if possible ? It should be like the following:
```python
In [5]: cnf_s = """key1:                                                                                    ...: key2: 2
   ...: """

In [6]: cnf = anyconfig.loads(cnf_s, ac_parser="yaml")

In [7]: cnf
Out[7]: {'key1': None, 'key2': 2}

In [8]: print(anyconfig.dumps(cnf, ac_parser="yaml", ac_safe=True, default_flow_style=False, indent=2))
key1: null
key2: 2

In [9]:
```

**Comment by ajays20078** [comment]
Thanks that works for yaml, but for json it still doesn't do pretty print.

If you load:

{
	"one": {
			"two" : 3
		},
	"two": {
			"three" :4
		}
}

and dump it, it prints

{"two": {"three": 4}, "one": {"two": 3}}

Is there a flag for this?

**Comment by ajays20078** [comment]
Actually indent=2 works with json as well, so this should work. Thanks for quick bug fix!

**Comment by ajays20078** [comment]
Closing this.
